Traceback (most recent call last):
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/scripts/data_preprocessing/lean_repo_setup.py", line 90, in <module>
    main()
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/scripts/data_preprocessing/lean_repo_setup.py", line 84, in main
    traced_file = mathlib_repo.get_traced_file("Mathlib/Data/Relqk2dq38z.lean")
AttributeError: 'LeanGitRepo' object has no attribute 'get_traced_file'
